/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        light: {
          background: "#FFFFFF",
          "background-secondary": "#F8FAFC",
          "background-muted": "#F1F5F9",
          foreground: "#1E293B",
          "foreground-secondary": "#334155",
          "foreground-muted": "#64748B",
          card: "#FFFFFF",
          "card-foreground": "#1E293B",
          border: "#E2E8F0",
          input: "#F1F5F9",
          ring: "#3B82F6",
          primary: "#3B82F6",
          "primary-foreground": "#FFFFFF",
          secondary: "#F1F5F9",
          "secondary-foreground": "#1E293B",
          success: "#10B981",
          warning: "#F59E0B",
          error: "#EF4444",
          info: "#3B82F6",
        },
        dark: {
          background: "#0F172A",
          "background-secondary": "#1E293B",
          "background-muted": "#334155",
          foreground: "#F1F5F9",
          "foreground-secondary": "#E2E8F0",
          "foreground-muted": "#94A3B8",
          card: "#1E293B",
          "card-foreground": "#F1F5F9",
          border: "#334155",
          input: "#334155",
          ring: "#60A5FA",
          primary: "#60A5FA",
          "primary-foreground": "#1E293B",
          secondary: "#334155",
          "secondary-foreground": "#F1F5F9",
          success: "#34D399",
          warning: "#FBBF24",
          error: "#F87171",
          info: "#60A5FA",
        },
      },
    },
  },
  plugins: [],
};
